### ISSUE TITLE
Wrong Feature Extraction

### ISSUE THREAD

**Issue by lilasrahis** [cynthi8/GNNUnlock#2]
Dear Erin,

Please check our gate-level Netlist parser in https://github.com/DfX-NYUAD/GNNUnlock to get our results.
Your feature extraction is not consistent with our proposed extraction in DATE'21 paper.
Lilas

**Comment by cynthi8** [comment]
Hi Lilas, 

I looked into how y'all were doing feature extraction with bitwidth-independent node types (ex. AND2_X0P7M_A9TH and AND3_X0P5M_A9TH both are considered as AND type nodes). Unfortunately, this change didn't improve the performance.

What made the ultimate difference was inserting self-loop edges for nodes connected to primary edges. This doesn't seem to be documented in the DATE'21 paper, but is present in your parser's adj_train and adj_full matrixs.

With this change, I get performance comparable to your parser. 
Erin
